name: double_pendulum_dynamical_system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pillow
  - ffmpeg
  - ipython
  - ipykernel
  - jupyter
  - notebook
